# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- script: |
    # go to the TF config subdir
    cd agent-terraform-pipeline

    # Use sed to set the TF statefile backend PAR in the provider.tf from pipeline vars
    sed -i 's|STATEFILE_PAR|$(PAR)|g' provider.tf

    cat provider.tf
    
    # run the Terraform
    terraform init
    terraform apply -var tenancy_ocid="$(TENANCY)" -var compartment_ocid="$(COMPARTMENT)"

  displayName: 'Run Terraform apply from repo as instance principal'
